{
	"patcher": {
		"fileversion": 1,
		"appversion": { "major": 8, "minor": 6, "revision": 0, "architecture": "x64", "modernui": 1 },
		"classnamespace": "box",
		"rect": [ 80.0, 100.0, 760.0, 720.0 ],
		"openinpresentation": 1,
		"boxes": [
			{ "box": { "id": "obj-title", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 40.0, 16.0, 600.0, 20.0 ], "text": "Look Mah, No Hands - transport + camera. OSC in on UDP 7400 -> transport.js (LiveAPI)." } },
			{ "box": { "id": "obj-u", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 40.0, 50.0, 110.0, 22.0 ], "text": "udpreceive 7400" } },
			{ "box": { "id": "obj-route", "maxclass": "newobj", "numinlets": 1, "numoutlets": 5, "outlettype": [ "", "", "", "", "" ], "patching_rect": [ 40.0, 90.0, 520.0, 22.0 ], "text": "route /transport/playstop /transport/return /transport/recordarm /transport/undo" } },
			{ "box": { "id": "obj-mPlay", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 40.0, 140.0, 70.0, 22.0 ], "text": "playstop" } },
			{ "box": { "id": "obj-mRtz", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 130.0, 140.0, 50.0, 22.0 ], "text": "rtz" } },
			{ "box": { "id": "obj-mRec", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 200.0, 140.0, 90.0, 22.0 ], "text": "recordarm" } },
			{ "box": { "id": "obj-mUndo", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 310.0, 140.0, 60.0, 22.0 ], "text": "undo" } },
			{ "box": { "id": "obj-js", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 40.0, 190.0, 120.0, 22.0 ], "text": "js transport.js" } },
			{ "box": { "id": "obj-jsnote", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 180.0, 193.0, 280.0, 20.0 ], "text": "(each action prints in the Max Console)" } },
			{ "box": { "id": "obj-midiin", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 620.0, 50.0, 60.0, 22.0 ], "text": "midiin" } },
			{ "box": { "id": "obj-midiout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 620.0, 90.0, 60.0, 22.0 ], "text": "midiout" } },
			{ "box": { "id": "obj-camnote", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 40.0, 248.0, 600.0, 20.0 ], "text": "CAMERA: click getvdevlist, read the console, type your camera's number; toggle auto-starts on load." } },
			{ "box": { "id": "obj-load", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "bang" ], "patching_rect": [ 120.0, 282.0, 64.0, 22.0 ], "text": "loadbang" } },
			{ "box": { "id": "obj-on", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 120.0, 316.0, 30.0, 22.0 ], "text": "1" } },
			{ "box": { "id": "obj-tog", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": [ "int" ], "patching_rect": [ 40.0, 282.0, 24.0, 24.0 ], "presentation": 1, "presentation_rect": [ 10.0, 258.0, 24.0, 24.0 ] } },
			{ "box": { "id": "obj-met", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "bang" ], "patching_rect": [ 40.0, 350.0, 64.0, 22.0 ], "text": "metro 33" } },
			{ "box": { "id": "obj-grab", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": [ "jit_matrix", "" ], "patching_rect": [ 40.0, 386.0, 110.0, 22.0 ], "text": "jit.grab 640 480" } },
			{ "box": { "id": "obj-pwin", "maxclass": "jit.pwindow", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 40.0, 422.0, 320.0, 240.0 ], "presentation": 1, "presentation_rect": [ 10.0, 10.0, 320.0, 240.0 ] } },
			{ "box": { "id": "obj-getlist", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 400.0, 316.0, 90.0, 22.0 ], "text": "getvdevlist", "presentation": 1, "presentation_rect": [ 44.0, 258.0, 90.0, 22.0 ] } },
			{ "box": { "id": "obj-num", "maxclass": "number", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 400.0, 350.0, 60.0, 22.0 ], "presentation": 1, "presentation_rect": [ 144.0, 258.0, 60.0, 22.0 ] } },
			{ "box": { "id": "obj-vdev", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 400.0, 386.0, 160.0, 22.0 ], "text": "close, vdevice $1, open", "presentation": 1, "presentation_rect": [ 214.0, 258.0, 116.0, 22.0 ] } },
			{ "box": { "id": "obj-print", "maxclass": "newobj", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 580.0, 386.0, 80.0, 22.0 ], "text": "print VDEV" } }
		],
		"lines": [
			{ "patchline": { "source": [ "obj-u", 0 ], "destination": [ "obj-route", 0 ] } },
			{ "patchline": { "source": [ "obj-route", 0 ], "destination": [ "obj-mPlay", 0 ] } },
			{ "patchline": { "source": [ "obj-route", 1 ], "destination": [ "obj-mRtz", 0 ] } },
			{ "patchline": { "source": [ "obj-route", 2 ], "destination": [ "obj-mRec", 0 ] } },
			{ "patchline": { "source": [ "obj-route", 3 ], "destination": [ "obj-mUndo", 0 ] } },
			{ "patchline": { "source": [ "obj-mPlay", 0 ], "destination": [ "obj-js", 0 ] } },
			{ "patchline": { "source": [ "obj-mRtz", 0 ], "destination": [ "obj-js", 0 ] } },
			{ "patchline": { "source": [ "obj-mRec", 0 ], "destination": [ "obj-js", 0 ] } },
			{ "patchline": { "source": [ "obj-mUndo", 0 ], "destination": [ "obj-js", 0 ] } },
			{ "patchline": { "source": [ "obj-midiin", 0 ], "destination": [ "obj-midiout", 0 ] } },
			{ "patchline": { "source": [ "obj-load", 0 ], "destination": [ "obj-on", 0 ] } },
			{ "patchline": { "source": [ "obj-on", 0 ], "destination": [ "obj-tog", 0 ] } },
			{ "patchline": { "source": [ "obj-tog", 0 ], "destination": [ "obj-met", 0 ] } },
			{ "patchline": { "source": [ "obj-met", 0 ], "destination": [ "obj-grab", 0 ] } },
			{ "patchline": { "source": [ "obj-grab", 0 ], "destination": [ "obj-pwin", 0 ] } },
			{ "patchline": { "source": [ "obj-grab", 1 ], "destination": [ "obj-print", 0 ] } },
			{ "patchline": { "source": [ "obj-getlist", 0 ], "destination": [ "obj-grab", 0 ] } },
			{ "patchline": { "source": [ "obj-num", 0 ], "destination": [ "obj-vdev", 0 ] } },
			{ "patchline": { "source": [ "obj-vdev", 0 ], "destination": [ "obj-grab", 0 ] } }
		]
	}
}
